# Generated by Django 3.1.14 on 2023-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('downloadcount', models.IntegerField(blank=True, default=0)),
                ('emailcount', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
